build_now:              'YES'
download_base_url:      http://downloads.sourceforge.net/openemu/
release_notes_base_url: http://openemu.sourceforge.net/rnotes/OpenEmu/
appcast_basefolder:     '/Users/jweinberg/Desktop/Appcast'
appcast_xml_name:       'appcast.xml'
keychain_privkey_name:  'Sparkle Private Key'
css_file_name:          'rnotes.css'
bundle_extension:       'app'