blank_issues_enabled: false

contact_links:
  - name: âš ï¸ğŸ•¹ Reporting problems guide â€” Looking for help? Read this first
    url: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems
    about: In order to reduce duplicate and low information issues opened, please read before opening a new one.
