build_now:              'YES'
download_base_url:      http://github.com/downloads/openemu/openemu/
release_notes_base_url: http://openemu.org/category/releasenotes/openemuqc/
appcast_basefolder:     '/Users/jweinberg/Desktop/Appcast'
appcast_xml_name:       'appcast_qc.xml'
keychain_privkey_name:  'QC Private Key'
css_file_name:          'rnotes.css'
product_name:           'OpenEmuQC'
bundle_extension:       'plugin'